# Generated by Django 4.2.5 on 2023-09-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
            },
        ),
        migrations.CreateModel(
            name='editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_username', models.CharField(max_length=100, unique=True)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_email', models.CharField(max_length=100, unique=True)),
                ('staff_phNumber', models.CharField(max_length=20)),
                ('staff_password', models.CharField(max_length=100)),
                ('staff_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.CharField(max_length=100)),
                ('stu_phNumber', models.CharField(max_length=20)),
                ('stu_password', models.CharField(max_length=100)),
                ('stu_address', models.TextField()),
                ('interested_category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursecategory')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.editor')),
            ],
        ),
    ]
